server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: 2024
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 